server:
  port: 8081
  
spring:
  application:
    name: customer-server
  datasource:
    url: jdbc:mysql://localhost:3306/brillioWave?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
    show-sql: true  
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
